title: "Flutterチュートリアル"
summary: "Flutterの基礎を学習していきましょう。\n# 使う技術やSass\n- go_router\n- riverpod\n- hooks\n- supabase\n- isar\n- Shared Preference\netc..."
topics: ["flutter", "dart"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 環境構築
  - 基本のウィジェット
  - アプリのテーマ設定
  - パッケージの選定基準について
  - 画面遷移
  - 状態管理の基礎
  - 状態管理_riverpod
  - 状態管理_riverpod_2
  - 非同期処理
  - ローカルデータベース
  - リモートデータベース
  - アーキテクチャ
  - push通知
  - 認証機能
  - Functions
  - テスト

