title: "Flutterチュートリアル"
summary: "Flutterの基礎を学習していきましょう。\n# 使う技術やSass\n- go_router\n- riverpod\n- hooks\n- supabase\n- isar\n- Shared Preference\netc..."
topics: ["flutter", "dart"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - env_setting
  - basic_widget
  - app_theme
  - package_selection
  - navigation
  - state_management_basic
  - state_management_riverpod
  - state_management_riverpod_2
  - asynchronous
  - local_database
  - remote_database
  - architecture
  - push_notifications
  - authentication
  - edge_functions
  - test

