name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  GCLOUD_PROJECT: visionary-flutter-playground

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ env.GCLOUD_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate Docker
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t "gcr.io/$GCLOUD_PROJECT/zenn-preview" .

      - name: Push Docker image
        run: docker push "gcr.io/$GCLOUD_PROJECT/zenn-preview"

      - name: Deploy to Cloud Run
        run: |
          service_name="visionary-flutter-playground"
          gcloud run deploy "$service_name" \
            --image "gcr.io/$GCLOUD_PROJECT/zenn-preview" \
            --port 8000 \
            --platform managed \
            --allow-unauthenticated \
            --region asia-northeast1
